#SET fish_color_autosuggestion 555\x1eyellow
#SET fish_color_command 87ffaf
#SET fish_color_comment red
#SET fish_color_cwd green
#SET fish_color_cwd_root ffd7d7
#SET fish_color_error red\x1e\x2d\x2dbold
#SET fish_color_escape cyan
#SET fish_color_history_current cyan
#SET fish_color_host \x2do\x1ecyan
#SET fish_color_match cyan
#SET fish_color_normal normal
#SET fish_color_operator cyan
#SET fish_color_param 00afff\x1ecyan
#SET fish_color_quote ffd787
#SET fish_color_redirection normal
#SET fish_color_search_match \x2d\x2dbackground\x3dpurple
#SET fish_color_status red
#SET fish_color_user \x2do\x1egreen
#SET fish_color_valid_path \x2d\x2dunderline
